import { pathToFileURL } from 'node:url';
const { chromium } = await import(process.env.PLAYWRIGHT_MODULE ? pathToFileURL(process.env.PLAYWRIGHT_MODULE).href : 'playwright');
import fs from 'node:fs';
import assert from 'node:assert/strict';
(async () => {
  fs.mkdirSync('outputs', { recursive: true });
  const browser = await chromium.launch({headless: true,...(process.env.CHROMIUM_EXECUTABLE ? { executablePath: process.env.CHROMIUM_EXECUTABLE } : {})});
  const page = await browser.newPage({viewport:{width:1280,height:900},deviceScaleFactor:1});
  const errors=[];
  page.on('pageerror', e=>errors.push(e.message));
  await page.goto(process.env.BASE || 'http://127.0.0.1:5174/',{waitUntil:'networkidle',timeout:60000});
  await page.waitForFunction(()=>window.blackglassReel,{timeout:20000});
  await page.locator('[data-reel]').scrollIntoViewIfNeeded();
  const readings=[];
  for(const [name,time] of [['brace',0],['lower',2.1],['pause',4.1],['drive',5.1],['lockout',5.8]]) {
    await page.evaluate(t=>window.blackglassReel.seek(t),time);
    await page.locator('.reel-stage').screenshot({path:`outputs/reel-${name}-desktop.png`});
    readings.push(await page.evaluate(()=>({cue:document.querySelector('[data-rep-cue]').innerText, shin:document.querySelector('[data-j="shin"]').style.transform,bar:document.querySelector('[data-bar-dot]').style.transform})));
  }
  assert.match(readings[2].cue,/Pause \/ 1 second/i);
  assert.match(readings[3].cue,/Drive \/ 1 second/i);
  assert.match(readings[4].cue,/Lockout/i);
  await page.locator('[data-reel-toggle]').click();
  await page.waitForTimeout(150);
  await page.emulateMedia({reducedMotion:'reduce'});
  await page.waitForTimeout(100);
  const frozen=await page.locator('[data-j="shin"]').first().getAttribute('style');
  await page.waitForTimeout(450);
  assert.equal(await page.locator('[data-j="shin"]').first().getAttribute('style'),frozen);
  assert.equal(await page.locator('[data-reel-toggle]').isDisabled(),true);
  await page.emulateMedia({reducedMotion:'no-preference'});
  assert.equal(await page.locator('[data-reel-toggle-text]').textContent(),'Play');
  await page.waitForTimeout(200);
  assert.equal(await page.locator('[data-j="shin"]').first().getAttribute('style'),frozen);
  await page.setViewportSize({width:390,height:844});
  await page.evaluate(()=>window.blackglassReel.seek(4.1));
  await page.locator('[data-reel]').scrollIntoViewIfNeeded();
  await page.locator('.reel-stage').screenshot({path:'outputs/reel-pause-mobile.png'});
  const bounds=await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,limbs:[...document.querySelectorAll('.rl-limb')].map(e=>{const r=e.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height}})}));
  assert.equal(bounds.width,bounds.scroll);
  await page.setViewportSize({width:1280,height:900});
  await page.evaluate(()=>window.blackglassReel.seek(0.6));
  await page.locator('[data-reel-toggle]').click();
  await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pagehide')));
  const hidden=await page.locator('[data-j="shin"]').first().getAttribute('style');
  await page.waitForTimeout(250);
  assert.equal(await page.locator('[data-j="shin"]').first().getAttribute('style'),hidden);
  await page.evaluate(()=>window.dispatchEvent(new PageTransitionEvent('pageshow')));
  await page.waitForTimeout(200);
  await page.evaluate(()=>document.querySelector('[data-reel]').remove());
  await page.waitForTimeout(200);
  assert.deepEqual(errors,[]);
  fs.writeFileSync('outputs/reel-review.json',JSON.stringify({status:'passed',readings,bounds,errors,checks:['keyframe phase timing','live reduced-motion freezes playback','preference removal does not restart','mobile no horizontal overflow','pagehide freezes','host removal cleanup']},null,2));
  await browser.close();
  console.log('Reel browser checks passed.');
})().catch(e=>{console.error(e);process.exit(1)});
